freifunk-berlin/ansible

roles/buildbot/files/buildsteps_feed.py, roles/buildbot/files/buildsteps_image.py
Github started warning about git:// being deprecated for unauthenticated
uses, so let's switch to https:// instead.
=> buildbot: Change git repo url from git:// to https://

roles/ff_wizard/templates/wizard-config.cfg.j2
This should fix the occasional "OperationalError: (psycopg2.OperationalError) SSL connection has been closed unexpectedly"
https://docs.sqlalchemy.org/en/14/core/engines.html#sqlalchemy.create_engine.params.pool_pre_ping
=> Check if pool is alive before running query

play.yml
minor correction on the playbook since the default role works on vpn03h since its a debian system
=> only exclude the 2 ubuntu systems

inventory/host_vars/monitor.berlin.freifunk.net, play.yml, templates/Caddyfile_monitor.j2
replace the installed nginx+certbot on monitor.ff... with caddy, similar to the config server etc.
=> add caddy for monitor.berlin.freifunk.net

roles/buildbot_worker/handlers/main.yml, roles/buildbot_worker/tasks/main.yml
Minor fixes for buildbot-worker role. There was some misspelled handler and there needs to be a directory for the worker info files.
Signed-off-by: Martin Hübner <martin.hubner@web.de>
=> buildbot-worker: Fix role

play.yml, roles/common/handlers/main.yml, roles/common/tasks/main.yml
This disallows root-login and pasword-based login on all servers. Fixes #54 
Signed-off-by: Martin Hübner <martin.hubner@web.de>
=> treewide. Disallow root-login on servers after provision.

.github/workflows/ansible-lint.yml
v2 of the checkout action is deprecated and should therefore be replaced with v3.
=> workflows: update checkout action to v3

.config/yaml-lint.yml, .github/workflows/yaml-lint.yml
This adds yaml-lint to the workflow and ignores ansible vault files in the worker directories.
=> workflows: add yaml-lint

roles/common/handlers/main.yml, roles/common/tasks/main.yml
Usually it will use ~4 GB
".. defaults to 10% .. of the size of the respective file system, but ...is capped to 4G. " (journald manpage)
This will limit its size down to 1 gb, which is enough in our usecase and limits the amount of data we store
=> limit journald size to 1 gb

roles/buildbot/files/master.cfg, roles/buildbot/files/packages.py, roles/buildbot/files/targets.py, roles/buildbot/templates/config.py.j2
Adds a "force-release" button for building release images. Versions that contain "-" or "snapshot" go to /unstable, others go to /stable. More info in freifunk-berlin/falter-builter#134.
Also: remove the 9 hour timeout on targets builds, build times vary too much.
=> buildbot: do releases

roles/buildbot/files/master.cfg, roles/buildbot/templates/config.py.j2
A few little fixes:
- buildbot: temporarily disable nightlies while broken
- buildbot: re-enable treeStableTimer
- buildbot: switch to alpine 3.18, edge has mkdir segfaults
=> buildbot: fix builds

play.yml, roles/tunneldigger/defaults/main.yml, roles/tunneldigger/handlers/main.yml, roles/tunneldigger/tasks/main.yml, roles/tunneldigger/templates/l2tp_broker.cfg.j2, roles/tunneldigger/templates/nftables.conf.j2
the newly set-up d.tunnel is now using a minimal debian 12.
Therefore i added it to the "propper" hosts (e.g. remove expections)
I also added needed dependencies and tadded smaller fixes for hosts with Predictable Network Interface renaming
=> fixes for tunneldigger

.github/workflows/linter.yml, .gitignore, README.md, ansible.cfg, inventory/hosts, requirements.txt, requirements.yml, roles/caddy/handlers/main.yml, roles/caddy/tasks/main.yml, roles/common/handlers/main.yml, roles/common/tasks/main.yml, roles/common/templates/collectd-ffberlin.conf.j2, roles/ff_monitor/handlers/main.yml, roles/ff_monitor/tasks/main.yml, roles/ff_monitor/templates/prometheus.j2, roles/ff_wizard/defaults/main.yml, roles/ff_wizard/handlers/main.yml, roles/ff_wizard/tasks/main.yml, roles/nipap/handlers/main.yml, roles/nipap/tasks/main.yml, roles/tunneldigger/handlers/main.yml, roles/tunneldigger/tasks/main.yml
A lot of small stuff:
- fixed a lot of linting errors (ansible-lint --fix will also "fix" yaml formating)
- updated dependencies and ansible version
- reduced the ansible_managed string to not change on every run
- removed collectd for our VMs
-  increased prometheus storage
=> fix smaller stuff like linting, remove old stuff, update dependencies

roles/ff_monitor/templates/config.local.php.j2
this PR adds new locations and also adds the existing gateway locations for which we will have SNMP statistics once we flash the gateways with a firmware containing https://github.com/freifunk-berlin/bbb-configs/commit/9a676abaa1c8d5c72d903f818ce8ee2ac68aca5a
=> monitor: add new locations and gateway locations

roles/buildbot/files/packages.py, roles/buildbot/files/targets.py, roles/buildbot/tasks/main.yml, roles/podman_fix/tasks/main.yml
Removing xz-utils in favor of zstd.
Also removed the old temporary podman fix, and manually removed the related APT repositories. Fixes `apt update`.
=> buildbot: need zstd for OpenWrt tarballs now

roles/buildbot/files/master.cfg, roles/buildbot/files/targets.py
- buildbot: use the new falter build script
- buildbot: filtering of broken targets not needed anymore
=> buildbot: new falter build script

templates/Caddyfile_website.j2
Google Search Console shows quite some 404s due to redirects only matching a single URL. This PR should fix that.
=> website: fix 404s by adding redirects

roles/buildbot/files/master.cfg, roles/buildbot/files/packages.py, roles/buildbot/files/targets.py
This is to help the autoupdater with devices that changed target names - e.g. Nanostation ath79/generic to ath79/tiny
(plus OpenWrt 24.10, and a little fix for an upcoming upgrade to Buildbot 4.x)
=> buildbot: OpenWrt 24.10, and combined profiles.json for autoupdater

roles/buildbot/files/targets.py
Trying to accelerate the targets builds a little bit. We'll see if it helps.
=> buildbot: build on ramdisks

roles/buildbot/files/targets.py
Both take by far the longest time to build - multiples of any other target. If we run them first we save hours potentially.
=> buildbot: run ath79/generic & ramips/mt7621 first to save time

roles/buildbot/files/targets.py
One more little fix :)
After building, the workers upload the results to buildbot as a tarball file. The filename includes target and the ID of the original parent build. With 0fa146a, there are now two builds of the same target (notunnel & tunneldigger) and with the right timing they can delete each other's upload.
Fix this by including the variant in the upload tarball filename.
=> buildbot: apply variant to tarball upload, avoid race condition
