freifunk-berlin/ansible

- roles/buildbot/files/generate_autoupdate_json.py
- roles/buildbot/tasks/main.yml
Adds a script for the next iteration of the autoupdater, which we need on the buildbot-server.
> buildbot: add script for generating autoupdate.json

- roles/common/tasks/main.yml
mc is a very useful tool for browsing directories.
> add tool mc to basic tools.

- inventory/hosts
- roles/ff_wizard/templates/uwsgi-ff-wizard.ini.j2
Quickfix for a few bugs discovered during prod deployment
> Config quickfix

- README.md
Some Fellow Freifunka didn't see on first glance, what this repo does. Updating the README file for clarification.
Signed-off-by: Martin Hübner <martin.hubner@web.de>
> Clarify content of repository

- play.yml
- roles/buildbot/files/packages.py
- roles/buildbot/files/symlink_build.sh
- roles/buildbot/files/targets.py
- roles/buildbot/tasks/main.yml
Merging https://github.com/freifunk-berlin/falter-builter/pull/126
needs to merge this too.
> Move scripts

- roles/buildbot/files/packages.py
- roles/buildbot/files/symlink_build.sh
- roles/buildbot/tasks/main.yml
Some more minor fixes for buildbot.
> More fixes

- play.yml
- roles/ff_monitor/files/create_node_geojson.py
- roles/ff_monitor/files/firmwaremetrics/classify-firmware.php
- roles/ff_monitor/files/firmwaremetrics/index.php
- roles/ff_monitor/handlers/main.yml
- roles/ff_monitor/tasks/main.yml
- roles/ff_monitor/templates/collectd.conf.j2
- roles/ff_monitor/templates/config.local.php.j2
- roles/ff_monitor/templates/grafana.ini.j2
- roles/ff_monitor/templates/prometheus.j2
- roles/ff_monitor/templates/prometheus.yml.j2
- templates/Caddyfile_monitor.j2
This commit adds a role thats reflects the current status of the monitoring server.
Caveats:
- It is not ready to fully redeploy that machine.
- It includes both collectd and prometheus (we are going to slowly phase out collectd)
> 39 add monitoring

- roles/ff_monitor/tasks/main.yml
- roles/ff_monitor/templates/config.local.php.j2
- templates/Caddyfile_monitor.j2
Remove old hosts from CGP Config.
Add fixes for the helperscripts
be more rigorous when cleaning up old metrics
> smaller fixes and cleanup

- templates/Caddyfile_monitor.j2
Add a redirect for links from external pages like hopglass
> add redirect for inbound links from e.g. hopglass

- README.md
Signed-off-by: Martin Hübner <martin.hubner@web.de>
> Readme.md: Add notic on machine base provision

- README.md
- Tutorials.md
This introduces a tutorial for adidng a buildbot worker to config management.
> README: Add tutorial on buildbot-worker and change structure

- .github/workflows/ansible-lint.yml
- requirements.yml
Fix order of the github action, add missing dependencies
> fix lint, add dependencies

- roles/ff_monitor/tasks/main.yml
- roles/ff_monitor/templates/prometheus.j2
- reduce the retention time from prometheus (180=>120)
- delete old metrics quicker from collectd
- fix linting issues
> reduce metrics retention

- roles/ff_monitor/templates/config.local.php.j2
in addition, add dhcpleases and snmp to the default plugin list
> monitor: update groups using as many regex as possible

- roles/ff_monitor/templates/config.local.php.j2
The changes are already active
> monitor: update regex for teufelsberg

- roles/ff_monitor/templates/config.local.php.j2
I added more groups for several locations. In addition I sorted the list and removed the closing php-tags as they are not required.
> monitor: groups for more locations + alphabetical sorting

- roles/buildbot/files/packages.py
- roles/buildbot/files/targets.py
Preparing 1.4.0 release. Whoop Whoop!
> packages/images: Reinclude xz for legacy branches

- inventory/hosts
- play.yml
- roles/common/templates/fail2ban-ffberlin.local.j2
- roles/ff_monitor/handlers/main.yml
- roles/ff_monitor/tasks/main.yml
- roles/ff_monitor/templates/grafana.ini.j2
- roles/ff_monitor/templates/prometheus.j2
- roles/ff_monitor/templates/prometheus.yml.j2
- templates/Caddyfile_monitor.j2
i did a ansible --check run against most of the hosts and these are the manual changes to the hosts (+ a bunch of other stuff that didn't work)
> Smaller fixes

- roles/buildbot/files/targets.py
Context: https://github.com/freifunk-berlin/falter-builter/pull/172
Test build: https://buildbot.berlin.freifunk.net/#/builders/3/builds/271 && https://firmware.berlin.freifunk.net/unstable/testbuildbot/
> buildbot: generate autoupdate.json for every build

- inventory/group_vars/buildbot
- roles/buildbot_worker/defaults/main.yml
There's an issue where it stops automatically refreshing the UI. Let's update anyway.
> buildbot: update to 4.3.0

- roles/buildbot/files/master.cfg
- roles/buildbot/files/packages.py
- roles/buildbot/files/targets.py
- roles/buildbot_worker/tasks/main.yml
- roles/buildbot_worker/templates/admin.j2
- roles/buildbot_worker/templates/host.j2
> buildbot: smallies
